#!/usr/bin/env bash
# OCI Homelab - Environment Setup Script
# Run this once on the VM after SSH-ing in to configure API keys and start services.
# Usage: bash /home/ubuntu/ai-pipeline/scripts/setup_env.sh

set -euo pipefail

ENV_FILE="/home/ubuntu/ai-pipeline/.env"
BASHRC="/home/ubuntu/.bashrc"
DAG_SRC="$(dirname "$0")/../dags/stock_pipeline.py"
AIRFLOW_DAGS_DIR="/home/ubuntu/airflow/dags"
AIRFLOW_HOME="/home/ubuntu/airflow"

# ---------------------------------------------------------------------------
# Colours
# ---------------------------------------------------------------------------
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}========================================"
echo "  OCI Homelab Environment Setup"
echo -e "========================================${NC}"
echo ""

# ---------------------------------------------------------------------------
# Prompt for API keys
# ---------------------------------------------------------------------------
echo -e "${YELLOW}Enter your API credentials (input is hidden):${NC}"
echo ""

read -rp "  GROQ_API_KEY (from console.groq.com): " GROQ_API_KEY
echo ""
read -rp "  TELEGRAM_BOT_TOKEN (from @BotFather): " TELEGRAM_BOT_TOKEN
echo ""
read -rp "  TELEGRAM_CHAT_ID (your user/group ID): " TELEGRAM_CHAT_ID
echo ""

if [[ -z "$GROQ_API_KEY" ]]; then
    echo -e "${RED}ERROR: GROQ_API_KEY cannot be empty.${NC}"
    exit 1
fi

# ---------------------------------------------------------------------------
# Write .env file
# ---------------------------------------------------------------------------
cat > "$ENV_FILE" <<EOF
# OCI Homelab Environment Variables
# Generated by setup_env.sh on $(date -u +"%Y-%m-%d %H:%M UTC")

GROQ_API_KEY=${GROQ_API_KEY}
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}

# PostgreSQL connection
DB_HOST=localhost
DB_PORT=5432
DB_NAME=ai_pipeline
DB_USER=aiuser
DB_PASSWORD=aipassword

# Airflow
AIRFLOW_HOME=/home/ubuntu/airflow
EOF

chmod 600 "$ENV_FILE"
echo -e "${GREEN}[OK] Written ${ENV_FILE}${NC}"

# ---------------------------------------------------------------------------
# Source .env on login
# ---------------------------------------------------------------------------
SOURCE_LINE="source ${ENV_FILE}"
if ! grep -qF "$SOURCE_LINE" "$BASHRC"; then
    echo "" >> "$BASHRC"
    echo "# OCI Homelab environment variables" >> "$BASHRC"
    echo "$SOURCE_LINE" >> "$BASHRC"
    echo -e "${GREEN}[OK] Added source line to ~/.bashrc${NC}"
else
    echo -e "${YELLOW}[SKIP] Source line already in ~/.bashrc${NC}"
fi

# Source for the current session
# shellcheck disable=SC1090
source "$ENV_FILE"

# ---------------------------------------------------------------------------
# Register API keys as Airflow Variables (fallback for DAG)
# ---------------------------------------------------------------------------
export AIRFLOW_HOME
airflow variables set groq_api_key      "$GROQ_API_KEY"      2>/dev/null || true
airflow variables set telegram_bot_token "$TELEGRAM_BOT_TOKEN" 2>/dev/null || true
airflow variables set telegram_chat_id   "$TELEGRAM_CHAT_ID"   2>/dev/null || true
echo -e "${GREEN}[OK] Airflow Variables updated${NC}"

# ---------------------------------------------------------------------------
# Copy DAG to Airflow dags folder
# ---------------------------------------------------------------------------
mkdir -p "$AIRFLOW_DAGS_DIR"

if [[ -f "$DAG_SRC" ]]; then
    cp "$DAG_SRC" "$AIRFLOW_DAGS_DIR/stock_pipeline.py"
    echo -e "${GREEN}[OK] DAG copied to ${AIRFLOW_DAGS_DIR}${NC}"
else
    echo -e "${YELLOW}[WARN] DAG source not found at ${DAG_SRC} — skipping copy.${NC}"
    echo "       Copy dags/stock_pipeline.py manually to ${AIRFLOW_DAGS_DIR}/"
fi

# ---------------------------------------------------------------------------
# Restart Airflow services
# ---------------------------------------------------------------------------
echo ""
echo "Restarting Airflow services..."

# Kill existing processes
pkill -f "airflow webserver" 2>/dev/null || true
pkill -f "airflow scheduler"  2>/dev/null || true
sleep 3

# Start fresh
nohup airflow webserver --port 8080 > "${AIRFLOW_HOME}/logs/webserver.log" 2>&1 &
echo $! > "${AIRFLOW_HOME}/webserver.pid"
echo -e "${GREEN}[OK] Airflow webserver started (PID $(cat "${AIRFLOW_HOME}/webserver.pid"))${NC}"

sleep 2

nohup airflow scheduler > "${AIRFLOW_HOME}/logs/scheduler.log" 2>&1 &
echo $! > "${AIRFLOW_HOME}/scheduler.pid"
echo -e "${GREEN}[OK] Airflow scheduler started (PID $(cat "${AIRFLOW_HOME}/scheduler.pid"))${NC}"

sleep 5

# ---------------------------------------------------------------------------
# Run test_setup.py to verify everything works
# ---------------------------------------------------------------------------
echo ""
echo "Running test_setup.py..."
if python3 /home/ubuntu/ai-pipeline/scripts/test_setup.py; then
    echo -e "${GREEN}[OK] test_setup.py passed${NC}"
else
    echo -e "${YELLOW}[WARN] test_setup.py reported failures — check output above${NC}"
fi

# ---------------------------------------------------------------------------
# Get public IP
# ---------------------------------------------------------------------------
PUBLIC_IP=$(curl -s https://ifconfig.me 2>/dev/null || echo "unknown")

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo ""
echo -e "${GREEN}========================================"
echo "  Setup Complete!"
echo "========================================"
echo ""
echo "  Airflow UI:  http://${PUBLIC_IP}:8080"
echo "  Credentials: admin / admin123"
echo ""
echo "  DAG:         stock_market_pipeline"
echo "  Schedule:    Mon–Fri at 06:00 UTC"
echo ""
echo "  To trigger manually:"
echo "  airflow dags trigger stock_market_pipeline"
echo ""
echo "  To tail logs:"
echo "  tail -f ~/airflow/logs/scheduler.log"
echo -e "========================================${NC}"
